### ISSUE TITLE
Unable to run the `EXAMPLE`

### ISSUE THREAD

**Issue by JasoonS** [jeddeloh/reason-apollo-client#7]
When I try run the example I get the following output:![image](https://user-images.githubusercontent.com/6032276/87156843-9a351900-c2bd-11ea-84f8-d66cbf6a7a1e.png)

I tried this at various recent commits including latest `master` and the tagged branch for `v0.0.1-alpha.2`.

I'm using npm v12.18.2, and simply run `yarn` in the `EXAMPLES` directory then `yarn start` to get the error.

Thanks in advance

**Comment by JasoonS** [comment]
Ok, update, I switched to the branch at tag `v0.0.1-alpha.1` and it worked when I commented out the following line (obviously just a typo):
![image](https://user-images.githubusercontent.com/6032276/87157765-05331f80-c2bf-11ea-845d-f689c66a8215.png)

I'll start using it from there

**Comment by jeddeloh** [comment]
It's saying `unknown option '-template-tag-return-type=...` which means graphql-ppx needs to be updated. I just released alpha.3. Give that a try and let me know if you encounter any issues. Thanks!

**Comment by jeddeloh** [comment]
Also note there are some configuration changes required: https://github.com/jeddeloh/reason-apollo-client/releases

**Comment by JasoonS** [comment]
Ah, ok thanks, I found the issue. I'll make a quick PR.

It looks like `template-tag-return-type` was renamed to `template-tag` in the latest version. :)
